const fs = require('fs');

const generateArtefact = (path, content) => {
    fs.writeFileSync(
        path,
      `/** -- This file is generated by the gastby-source-silverstripe plugin. Do not modify. -- **/
      
      ${content}
      `
    );
      
};

module.exports = generateArtefact;
